version: '3.1'

services:
  kegtrack:
    container_name: kegtrack_site
    image: rawestmoreland/kegtrack_site:prod
    ports:
      - "8080:80"
    networks:
      kegtrack_network:
        aliases:
          - kegtrack


networks:
  kegtrack_network:
    name: kegtrack_network